server:
  port: 8091

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
spring:
  cloud:
    openfeign:
      client:
        config:
          usermgmt-ms:
            url: http://usermgmt-service-ms.absolutehealth.svc.cluster.local:80/usermgmt
          shopping-cart-ms:
            url: http://shopping-cart-ms.absolutehealth.svc.cluster.local:80/shoppingCart
          product-catalog-ms:
            url: http://product-catalog-ms.absolutehealth.svc.cluster.local:80/catalog/product
          product-inventory-controller:
            url: http://product-catalog-ms.absolutehealth.svc.cluster.local:80/catalog/inventory
          offer-mgmt-coupons-controller:
            url: http://offer-management-ms.absolutehealth.svc.cluster.local:80/coupon/v1
springdoc:
  api-docs:
    path: /v3/checkout-service-docs