apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  application-dev.yaml: |
    spring:
      cloud:
        openfeign:
          client:
            config:
              usermgmt-ms:
                url: http://usermgmt-service-ms.absolutehealth.svc.cluster.local:80/usermgmt
              shopping-cart-ms:
                url: http://shopping-cart-ms.absolutehealth.svc.cluster.local:80/shoppingCart
              product-catalog-ms:
                url: http://product-catalog-ms.absolutehealth.svc.cluster.local:80/catalog/product
              product-inventory-controller:
                url: http://product-catalog-ms.absolutehealth.svc.cluster.local:80/catalog/inventory
              offer-mgmt-coupons-controller:
                url: http://offer-management-ms.absolutehealth.svc.cluster.local:80/coupon/v1
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
    server:
      port: {{ .Values.app.port }}
    springdoc:
      api-docs:
        path: /v3/checkout-service-docs
